services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: contract-followup-app
    ports:
      - "80:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000

networks:
  default:
    driver: bridge